"""empty message

Revision ID: 3cf9ed8213a7
Revises: fa8a4b8b696d
Create Date: 2022-10-03 15:54:32.499072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf9ed8213a7'
down_revision = 'fa8a4b8b696d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
