"""empty message

Revision ID: 59272a32caa7
Revises: 3cf9ed8213a7
Create Date: 2022-10-03 16:21:41.379745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59272a32caa7'
down_revision = '3cf9ed8213a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website_link')
    # ### end Alembic commands ###
